//FILE: todo_model.dart
import 'package:hive/hive.dart';

//specify name of the part file which will be generated by hive_generator
part 'todo_model.g.dart';
 
//Specify the HiveType with a type id between 0 and 233
//NOTE: No two TypeAdapters can have the same typeId
@HiveType(typeId: 0)
class Todo {
  //Annotate class members with HiveField with each 
  //HiveField having incrementing index
  @HiveField(0)
  String title;
  @HiveField(1)
  String description;
  
  //Default value can be specified if needed
  @HiveField(3, defaultValue: false)
  bool isDone;
  
  Todo({
    required this.title,
    required this.description,
    this.isDone = false,
  });
}
